import { useMemo, useState } from "react";
import type { ChartResult, ChartRow, TransitContact } from "../../../server/astronomy";

const colors: Record<string, string> = { Sun: "#e4b83f", Moon: "#f4f1e8", Mercury: "#55b9bd", Venus: "#e78eb4", Mars: "#de5f58", Jupiter: "#b7a2dc", Saturn: "#9299a6", Uranus: "#58bda7", Neptune: "#8997dc", Pluto: "#c68bc9", "North Node": "#63b890", "South Node": "#d38b52" };
const aspectColors: Record<TransitContact["aspect"], string> = { conjunction: "#dcae3f", sextile: "#57b981", square: "#d95b58", trine: "#4eaf79", opposition: "#dc6960" };
const zodiacGlyphs = ["♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓"];
const shortName = (name: string) => name === "North Node" ? "NN" : name === "South Node" ? "SN" : name === "Ascendant" ? "ASC" : name === "Descendant" ? "DSC" : name.slice(0, 2);
const point = (longitude: number, radius: number, center: number) => { const angle = (longitude - 90) * Math.PI / 180; return { x: center + Math.cos(angle) * radius, y: center + Math.sin(angle) * radius }; };
const normalize = (value: number) => (value % 360 + 360) % 360;

function DetailRow({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-white/5 py-2 last:border-0"><span className="text-slate-500">{label}</span><span className="text-right text-slate-200">{value}</span></div>; }

export function ChartWheel({ chart }: { chart: ChartResult }) {
  const [selectedHouse, setSelectedHouse] = useState<number | null>(null);
  const [selectedPoint, setSelectedPoint] = useState<{ kind: "natal" | "transit"; row: ChartRow } | null>(null);
  const size = 720; const center = size / 2; const outerRadius = 318; const natalRadius = 252; const transitRadius = 205; const houses = chart.houses.slice(0, 12);
  const natalRows = useMemo(() => [...chart.movingBodies, chart.ascendant, chart.descendant, chart.northNode, chart.southNode], [chart]);
  const transitRows = useMemo(() => chart.transits.filter(row => ["Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "North Node", "South Node"].includes(row.name)), [chart]);
  const natalByName = useMemo(() => new Map(natalRows.map(row => [row.name, row])), [natalRows]);
  const aspects = useMemo(() => transitRows.flatMap(transit => transit.natalContacts.map(contact => { const natal = natalByName.get(contact.natalName); return natal ? { transit, natal, contact } : null; }).filter(Boolean) as Array<{ transit: ChartRow; natal: ChartRow; contact: TransitContact }>), [transitRows, natalByName]);
  const activeHouse = selectedHouse ? houses[selectedHouse - 1] : null;
  const activeRows = selectedHouse ? natalRows.filter(row => row.house === selectedHouse) : [];
  const focusTitle = selectedPoint ? `${selectedPoint.kind === "transit" ? "Transit" : "Natal"} ${selectedPoint.row.name}` : selectedHouse ? `House ${selectedHouse}` : "Chart focus";
  const focusDescription = selectedPoint ? selectedPoint.kind === "transit" ? "A moving body in the selected transit moment, shown against the natal foundation." : "A birth-chart placement in the enduring layer of the wheel." : selectedHouse ? "Click any planet or aspect to move the focus from the house to a specific pattern." : "Select a house, planet, or aspect to inspect the chart interactively.";

  return <div className="chart-wheel-shell rounded-2xl border border-amber-100/10 bg-[#191a1c] p-3 shadow-2xl shadow-black/40 sm:p-5">
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[0.22em] text-amber-200"><span className="h-1.5 w-1.5 rounded-full bg-amber-300 shadow-[0_0_10px_rgba(228,184,63,.9)]"/>Interactive chart wheel</div><div className="mt-1 text-sm text-slate-400">Tap a house, placement, or aspect to reveal its context.</div></div><div className="flex flex-wrap gap-3 text-[11px] text-slate-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#e4b83f]"/>Natal</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#55b9bd]"/>Transit</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#d95b58]"/>Aspect</span></div></div>
    <div className="grid items-center gap-5 xl:grid-cols-[minmax(0,1fr)_230px]">
      <div className="mx-auto w-full max-w-[720px] overflow-hidden rounded-2xl border border-white/10 bg-[#111214] p-1 shadow-[inset_0_1px_0_rgba(255,255,255,.06)] sm:p-3"><svg viewBox={`0 0 ${size} ${size}`} className="h-auto w-full" role="img" aria-label="Interactive natal and transit astrology chart wheel">
        <defs><filter id="wheelGlow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><radialGradient id="wheelCore"><stop offset="0" stopColor="#303236"/><stop offset="1" stopColor="#151618"/></radialGradient></defs>
        <circle cx={center} cy={center} r={outerRadius} fill="#e9e7e2" stroke="#fbfaf5" strokeWidth="3"/><circle cx={center} cy={center} r="300" fill="none" stroke="#9b9b98" strokeWidth="1"/><circle cx={center} cy={center} r="286" fill="none" stroke="#777977" strokeWidth="1" strokeDasharray="1 8"/><circle cx={center} cy={center} r="264" fill="url(#wheelCore)" stroke="#8d8f90" strokeWidth="2"/><circle cx={center} cy={center} r={natalRadius} fill="#242629" stroke="#a8aaa8" strokeOpacity=".8"/><circle cx={center} cy={center} r={transitRadius} fill="#1b1d20" stroke="#c2c3bd" strokeOpacity=".65"/><circle cx={center} cy={center} r="133" fill="none" stroke="#8d8f90" strokeOpacity=".8"/><circle cx={center} cy={center} r="74" fill="none" stroke="#777a7a" strokeOpacity=".55"/>
        {zodiacGlyphs.map((glyph, i) => { const p = point(i * 30 + 15, 301, center); return <text key={glyph} x={p.x} y={p.y} fill={i % 2 === 0 ? "#bd3543" : "#2d6e9e"} fontSize="24" textAnchor="middle" dominantBaseline="middle" fontFamily="Georgia, serif">{glyph}</text>; })}
        {houses.map((longitude, i) => { const a = point(longitude, 133, center); const b = point(longitude, outerRadius, center); const label = point(normalize(longitude + 15), 281, center); const house = i + 1; const active = selectedHouse === house; return <g key={`house-${house}`} onClick={() => { setSelectedHouse(house); setSelectedPoint(null); }} className="cursor-pointer"><path d={`M ${center} ${center} L ${a.x} ${a.y} A 133 133 0 0 1 ${point(houses[(i + 1) % 12], 133, center).x} ${point(houses[(i + 1) % 12], 133, center).y} Z`} fill={active ? "rgba(103,232,249,.12)" : "transparent"} stroke="none"/><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={active ? "#67e8f9" : i === 0 || i === 6 ? "#f0abfc" : "#64748b"} strokeOpacity={active ? ".95" : i === 0 || i === 6 ? ".8" : ".45"} strokeWidth={active ? "2.2" : i === 0 || i === 6 ? "1.6" : "1"}/><text x={label.x} y={label.y} fill={active ? "#67e8f9" : "#8491aa"} fontSize={active ? "13" : "10"} fontWeight={active ? "700" : "500"} textAnchor="middle" dominantBaseline="middle">{house}</text></g>; })}
        {aspects.map(({ transit, natal, contact }, index) => { const a = point(natal.longitude, natalRadius, center); const b = point(transit.longitude, transitRadius, center); const color = aspectColors[contact.aspect]; return <g key={`aspect-${transit.name}-${natal.name}-${index}`} onClick={() => { setSelectedPoint({ kind: "transit", row: transit }); setSelectedHouse(null); }} className="cursor-pointer"><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={color} strokeOpacity=".12" strokeWidth="8"/><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={color} strokeOpacity=".8" strokeWidth="1.6" strokeDasharray={contact.aspect === "square" || contact.aspect === "opposition" ? "5 5" : "none"}/><title>{transit.name} {contact.aspect} natal {natal.name} · {contact.orb.toFixed(1)}° orb</title></g>; })}
        {natalRows.map(row => { const p = point(row.longitude, natalRadius, center); const label = point(row.longitude, 277, center); const color = colors[row.name] ?? "#c4b5fd"; const active = selectedPoint?.row.name === row.name && selectedPoint.kind === "natal"; return <g key={`natal-${row.name}`} onClick={() => { setSelectedPoint({ kind: "natal", row }); setSelectedHouse(null); }} className="cursor-pointer"><line x1={center} y1={center} x2={p.x} y2={p.y} stroke={color} strokeOpacity=".16"/><circle cx={p.x} cy={p.y} r={active ? "9" : "6.5"} fill={color} stroke="#070b16" strokeWidth="2" filter={active ? "url(#wheelGlow)" : undefined}/><text x={label.x} y={label.y} fill={color} fontSize="11" fontWeight={active ? "700" : "500"} textAnchor="middle" dominantBaseline="middle">{shortName(row.name)}</text><title> Natal {row.name} · {row.display}</title></g>; })}
        {transitRows.map(row => { const p = point(row.longitude, transitRadius, center); const label = point(row.longitude, 218, center); const color = colors[row.name] ?? "#22d3ee"; const active = selectedPoint?.row.name === row.name && selectedPoint.kind === "transit"; return <g key={`transit-${row.name}`} onClick={() => { setSelectedPoint({ kind: "transit", row }); setSelectedHouse(null); }} className="cursor-pointer"><circle cx={p.x} cy={p.y} r={active ? "8" : "5.5"} fill={color} stroke="#06101a" strokeWidth="2" filter={active ? "url(#wheelGlow)" : undefined}/><text x={label.x} y={label.y} fill={color} fontSize="10" fontWeight={active ? "700" : "500"} textAnchor="middle" dominantBaseline="middle">{shortName(row.name)}</text><title>Transit {row.name} · {row.display}</title></g>; })}
        <line x1={center - outerRadius} y1={center} x2={center + outerRadius} y2={center} stroke="#737675" strokeOpacity=".55"/><line x1={center} y1={center - outerRadius} x2={center} y2={center + outerRadius} stroke="#737675" strokeOpacity=".55"/><text x={center} y={center - 7} fill="#f4f1e8" fontSize="15" textAnchor="middle" fontFamily="Playfair Display, Georgia, serif">Firmament</text><text x={center} y={center + 15} fill="#aeb0ad" fontSize="10" textAnchor="middle">natal · transit · aspect field</text>
      </svg></div>
      <aside className="rounded-2xl border border-cyan-200/10 bg-white/[0.035] p-4"><div className="mb-4 flex items-center justify-between"><span className="text-[10px] uppercase tracking-[0.2em] text-cyan-300">Selected focus</span><button type="button" onClick={() => { setSelectedHouse(null); setSelectedPoint(null); }} className="text-[10px] text-slate-500 hover:text-white">Reset</button></div><h3 className="font-serif text-2xl text-white">{focusTitle}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{focusDescription}</p>{selectedHouse && activeHouse !== undefined && <div className="mt-5 space-y-1"><DetailRow label="Cusp" value={activeHouse ? `${activeHouse.toFixed(2)}°` : "—"}/><DetailRow label="Placements" value={`${activeRows.length}`}/>{activeRows.map(row => <button type="button" key={row.name} onClick={() => setSelectedPoint({ kind: "natal", row })} className="mt-2 block w-full rounded-lg border border-white/5 bg-black/10 px-3 py-2 text-left text-xs text-slate-300 hover:border-cyan-200/30 hover:text-white">{row.name}<span className="float-right text-cyan-200">{row.display}</span></button>)}</div>}{selectedPoint && <div className="mt-5 space-y-1"><DetailRow label="Position" value={selectedPoint.row.display}/><DetailRow label="House" value={`House ${selectedPoint.row.house}`}/><DetailRow label="Layer" value={selectedPoint.kind === "transit" ? "Current transit" : "Natal foundation"}/>{selectedPoint.kind === "transit" && <div className="mt-4 space-y-2"><div className="text-[10px] uppercase tracking-[0.18em] text-rose-200">Natal contacts</div>{(selectedPoint.row as ChartResult["transits"][number]).natalContacts?.length ? (selectedPoint.row as ChartResult["transits"][number]).natalContacts.map((contact, index) => <div key={`${contact.natalName}-${index}`} className="rounded-lg border border-white/5 bg-black/10 px-3 py-2 text-xs text-slate-300"><span className="text-white">{contact.aspect}</span> {contact.natalName}<span className="float-right text-slate-500">{contact.orb.toFixed(1)}°</span></div>) : <div className="text-xs text-slate-500">No major contact within 3°.</div>}</div>}</div>}</aside>
    </div>
    <div className="mt-4 grid grid-cols-2 gap-2 text-[11px] text-slate-500 sm:grid-cols-4"><span>Asc {chart.ascendant.display}</span><span>Desc {chart.descendant.display}</span><span>NN {chart.northNode.display}</span><span>SN {chart.southNode.display}</span></div>
  </div>;
}
